# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
warnings_are_errors: true
sudo: required

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
